### ISSUE TITLE
Throw an Exception or log an error when there is no grid model at the specified csv directory path

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/simona#605]
Currently the simulation just creates an empty grid and then speedruns through time without calculating anything leaving you wondering whats going on. We should log a warning or thrown an exception so that the user knowas what happened

**Comment by staudtMarius** [comment]
Can you provide an example to reproduce this behavior?

**Comment by staudtMarius** [comment]
At the time this issue was created, SIMONA was still using the [PSDM version 3.0.0](https://github.com/ie3-institute/PowerSystemDataModel/releases/tag/3.0.0).
In the [version 4.0.0](https://github.com/ie3-institute/PowerSystemDataModel/releases/tag/4.0.0) some changes were made to the reading of data sources. One of them was changing from returning empty optionals to throwing exceptions.
